language: 
  - cpp

sudo: required

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

# osx_image: xcode61

compiler:
  - gcc

git:
  submodules: false

before_install:
  - export AUDIODEV=null
  # SIMULATE GUI (DISPLAY)
  - export DISPLAY=:99.0
  #- if [$TRAVIS_OS_NAME == linux]; then "sh -e /etc/init.d/xvfb start"; fi

install:
  - chmod +x travis_install.sh
  - ./travis_install.sh

before_script:
  # GET externals
  - travis_retry git submodule update --init --recursive

script:
  - chmod +x travis_script.sh
  - ./travis_script.sh
