language: 
  - cpp
  
os:
  - linux
  - osx

osx_image: xcode61

compiler:
  - gcc
  
git:
  submodules: false
  
before_install:
  - echo $TRAVIS_OS_NAME
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  # We need this line to have g++4.8 available in apt
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get install -qq gcc-4.8 g++-4.8; fi
  # We want to compile with g++ 4.8 when rather than the default g++
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get install -y libglu1-mesa-dev && sudo apt-get install -q -y --no-install-recommends libasound2-dev; fi

before_script:
  # Get externals
  - git submodule update --init --recursive
  - SOURCE_FOLDER="$PWD"
  - cd ..
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar -xvz emsdk-portable.tar.gz
  - ls -l
  - cd emsdk-portable
  - ./emsdk update
  - ./emsdk install latest
  - ./emsdk activate latest
  - ls -l
  - cd $SOURCE_FOLDER
  
script:
  - uname -a
  - $CXX --version
  - ./cmake_ems.sh emsbuild && cd ../emsbuild && make && make test
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./cmake_linux.sh linuxbuild && cd ../linuxbuild && make && make test; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./cmake_osx.sh osxbuild && cd ../osxbuild && xcodebuild -target ALL_BUILD && xcodebuild -target RUN_TESTS; fi
