language: cpp
compiler:
  - gcc
git:
  submodules: false
before_install:
  - free -tm
  - git submodule update --init --recursive
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - bash -e /etc/init.d/xvfb start
  - if [ $PACKAGE_UPLOAD ]; then travis_retry sudo apt-get install -q -y rpm; fi;
  - sudo apt-get install libglu1-mesa-dev
  - sudo apt-get install libasound2-dev
  - free -tm

script:
  - uname -a
  - $CXX --version
  - ./cmake_linux.sh linuxbuild
  - cd ..
  - cd linuxbuild
  - make
  - make test
