language: cpp

compiler:
  - gcc
git:
  submodules: false
  
before_install:
  - git submodule update --init --recursive
  # We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get --purge autoremove g++
  - sudo apt-get --purge autoremove gcc
  - sudo apt-get install -qq gcc-4.8 g++-4.8 
  # We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo apt-get install libglu1-mesa-dev
  - sudo apt-get install libasound2-dev

script:
  - uname -a
  - $CXX --version
  - ./cmake_linux.sh linuxbuild
  - cd ..
  - cd linuxbuild
  - make
  - make test
