language: cpp
compiler:
  - gcc
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
  - sudo apt-get install libglu1-mesa-dev
  - sudo apt-get install libasound2-dev
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script:
  - $CXX --version
  - ./cmake_linux.sh linuxbuild
  - cd ..
  - cd linuxbuild
  - make
  - make test
