language: 
  - cpp

sudo: required

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

# osx_image: xcode61

compiler:
  - gcc

git:
  submodules: false

before_install:
  - "export AUDIODEV=null"
  # SIMULATE GUI (DISPLAY)
  - "export DISPLAY=:99.0"
  - if [$TRAVIS_OS_NAME == linux]; then "sh -e /etc/init.d/xvfb start"; fi
before_install:
  # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - chmod +x travis_install.sh
  - ./travis_install.sh

before_script:
  # GET externals
  - travis_retry git submodule update --init --recursive

script:
  - chmod +x travis_script.sh
  - ./travis_script.sh
