language: cpp
compiler:
  - gcc
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - sudo apt-get install libxrandr-dev
  - sudo apt-get install libglapi-mesa
  - sudo apt-get install libgl1-mesa-glx
  - sudo apt-get install libgl1-mesa-dev
  - sudo apt-get install libxext-dev
  - sudo apt-get install libxrender-dev
  - sudo apt-get install g++-multilib
  - sudo apt-get install libglu1-mesa-dev
  - sudo apt-get install libasound2-dev

script:
  - uname -a
  - $CXX --version
  - ./cmake_linux.sh linuxbuild
  - cd ..
  - cd linuxbuild
  - make
  - make test
