language: cpp
compiler:
  - gcc
  - clang
  before_install: 
  - sudo apt-get install libasound2-dev
# Change this to your needs
script: ./cmake_linux.sh linuxbuild && cd linuxbuild && make && make test
