language: 
  - cpp
os:
  - linux
  - osx

osx_image: xcode61

compiler:
  - gcc

git:
  submodules: false

before_install:
  # SIMULATE GUI (DISPLAY)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - sudo ./travis_install.sh

before_script:
  # GET externals
  - git submodule update --init --recursive

script:
  - sudo ./travis_script.sh
