language: 
  - cpp

sudo: required

os:
  - linux
  - osx

# osx_image: xcode61

compiler:
  - gcc

git:
  submodules: false

install:
  - chmod +x travis_install.sh
  - ./travis_install.sh

before_script:
  # GET externals
  - travis_retry git submodule update --init --recursive

script:
  - chmod +x travis_script.sh
  - ./travis_script.sh
