language: 
  - cpp
  - objective-c

compiler:
  - gcc
  - clang
  
git:
  submodules: false
  
matrix:
  - LINUX=1
  - OSX=1
  
before_install:
  - if [ $LINUX ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  # We need this line to have g++4.8 available in apt
  - if [ $LINUX ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ $LINUX ]; then sudo apt-get update -qq; fi
  - if [ $OSX ]; then brew update && brew install llvm && brew link --force llvm; fi

install:
  - if [ $LINUX ]; then sudo apt-get install -qq gcc-4.8 g++-4.8; fi
  # We want to compile with g++ 4.8 when rather than the default g++
  - if [ $LINUX ]; thensudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [ $LINUX ]; then sudo apt-get install -y libglu1-mesa-dev && sudo apt-get install -y libasound2-dev; fi

before_script:
  # Get externals
  - git submodule update --init --recursive
  
script:
  - uname -a
  - $CXX --version
  - if [ $LINUX ]; ./cmake_linux.sh linuxbuild && cd .. && cd linuxbuild && make && make test; fi
  - if [ $OSX ]; ./cmake_osx.sh osxbuild && cd .. && cd osxbuild && xcodebuild; fi
