language: 
  - cpp

compiler:
  - gcc
  - clang
  
git:
  submodules: false
  
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  # We need this line to have g++4.8 available in apt
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then travis_retry brew update && brew install llvm && brew link --force llvm; fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get install -qq gcc-4.8 g++-4.8; fi
  # We want to compile with g++ 4.8 when rather than the default g++
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get install -y libglu1-mesa-dev && sudo apt-get install -y libasound2-dev; fi

before_script:
  # Get externals
  - git submodule update --init --recursive
  
script:
  - uname -a
  - $CXX --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./cmake_linux.sh linuxbuild; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd ../linuxbuild; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd make && make test; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./cmake_osx.sh osxbuild; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd ../osxbuild; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then xcodebuild; fi
