language: cpp

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang
  
git:
  submodules: false
  
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  # We need this line to have g++4.8 available in apt
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm && brew link --force llvm; fi
  # Get externals
  - git submodule update --init --recursive

install:
  - if [ $TRAVIS_OS_NAME == linux ]; sudo apt-get install -y -q gcc-4.8 g++-4.8; fi
  # We want to compile with g++ 4.8 when rather than the default g++
  - if [ $TRAVIS_OS_NAME == linux ]; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [ $TRAVIS_OS_NAME == linux ]; sudo apt-get install -y libglu1-mesa-dev && sudo apt-get install -y libasound2-dev; fi

script:
  - uname -a
  - $CXX --version
  - if [ $TRAVIS_OS_NAME == linux ]; ./cmake_linux.sh linuxbuild && cd .. && cd linuxbuild && make && make test; fi
  - if [ $TRAVIS_OS_NAME == osx ]; ./cmake_osx.sh osxbuild && cd .. && cd osxbuild && xcodebuild; fi
